### ISSUE TITLE
Adding pyh5md conda-forge conda package

### ISSUE THREAD

**Issue by edisj** [pdebuyl/pyh5md#16]
Hello,

I'm Edis, an undergraduate at ASU working with Dr. Oliver Beckstein and [Beckstein Lab](https://becksteinlab.physics.asu.edu/) over the summer as an REU student. 

The project I've been working on is implementing an h5md file coordinate reader/writer in MDAnalysis, where I've been using the pyh5md library to create and read from .h5md files. [Here's](https://github.com/MDAnalysis/mdanalysis/pull/2787) a link to the issue on MDA where some of the progress has been documented. 

I've opened this issue because we eventually need a pyh5md conda package for MDA and we are happy to help :).

**Comment by pdebuyl** [comment]
Hello Edis,

Nice iniative to include H5MD in MDAnalysis :-) I wrote a message in the related PR to present the situation with pyh5md. Let me know what you think and what plan you pick to include the writer functionality.

Cheers,
Pierre

**Comment by edisj** [comment]
Hey Dr. de Buyl, 

Thanks for the quick reply!

After talking to Oliver I think we're going to use h5py for our MDA reader and borrow code from pyh5md for the writer. Do you mind if I ask you questions along the way as I try to understand exactly how pyh5md works?

Thanks,
Edis

**Comment by pdebuyl** [comment]
I think that this is a good plan. You can ask questions in a github issue or by email. My email is available at https://www.kuleuven.be/wieiswie/en/person/00092351 (the page has spam prevention JS - I don't write it in plain online).

**Comment by pdebuyl** [comment]
@edisj I think that this issue can be closed.
