### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by khinsen** [pdebuyl/pyh5md#5]
Sooner or later pyh5md should have a test suite. And sooner is better than later in my opinion. I'd be happy to start writing some tests, but we (all contributors) should agree on the tools for this. My personal favorite is nose, which allows much more light-weight tests than Python's unittest module. On the other hand, it's one more piece to install (only for contributors, not for users).

**Comment by pdebuyl** [comment]
I added a pytest based test. It is very easy and takes care of temporary directories.

You can have a look at https://github.com/pdebuyl/pyh5md/tree/1.0-dev

**Comment by pdebuyl** [comment]
The testing is a bit minimal but I consider the issue closed until further notice :-)
